name: ðŸš€ Deploy proyecto completo al VPS

on:
  push:
    branches:
      - "main"   # Se ejecuta al hacer push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Checkout del repositorio
        uses: actions/checkout@v4

      - name: ðŸ§³ Copiar archivos al VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-compose.yml
            docker-cliente/**
            docker-notificacion/**
          target: ~/root/TestLD

      - name: ðŸš€ Desplegar en el VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/root/TestLD
            docker compose down
            docker compose build --no-cache
            docker compose up -d
